### ISSUE TITLE
Correct key is not correct?

### ISSUE THREAD

**Issue by lapkritinis** [MrEmpy/Crackme#1]
Hello, I have tried to "solve it" - but it doesn't accept "correct" key unless I change `scanf("%10s", input_key);` to `scanf("%20s", input_key);` Is it bug or I just dont know something?

**Comment by brosck** [comment]
Hello lapkritinis,

I just tested your finding and it was identified as a bug I forgot to fix when I was assembling the code. The problem is already fixed.

Thanks for reporting,
